### ISSUE TITLE
re-adding files in exact_ directories disrupts unrelated templates

### ISSUE THREAD

**Issue by r-ricci** [twpayne/chezmoi#4824]
## To reproduce

```sh
$ mkdir test
$ > test/chezmoi.toml
$ chezmoi -c test/chezmoi.toml -S test/source init
$ mkdir dir
$ echo hello > dir/a
$ chezmoi -c test/chezmoi.toml -S test/source add dir/a
$ chezmoi -c test/chezmoi.toml -S test/source chattr exact dir
$ echo hello > test/source/exact_dir/b.tmpl
$ chezmoi -c test/chezmoi.toml -S test/source apply
$ echo hello2 > dir/a
$ chezmoi -c test/chezmoi.toml -S test/source re-add dir/a
$ ls test/source/exact_dir/b*
test/source/exact_dir/b
```

`b` is no longer a template now. But only `a` has been changed and passed to the command.

`git bisect` points to 7ee10715b4e2df9fe2cefee124f1eedb6fc10179.

`re-add`ing the whole directory works as expected, as does `add`ing `dir/a`. `add dir` rightfully asks the user for what to do.

## Expected behavior

When re-adding an individual file in a `exact_` directory, unrelated files in the same directory and their corresponding templates in the source should be unaffected.

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
RESULT    CHECK                       MESSAGE
ok        version                     v2.67.1, commit v2.67.1, built at 2025-11-30, built by xbps
warning   latest-version              v2.68.1
ok        os-arch                     linux/amd64 (Void)
ok        uname                       Linux desktop0a 6.12.60_1 #1 SMP PREEMPT_DYNAMIC Mon Dec  1 22:36:17 UTC 2025 x86_64 GNU/Linux
ok        go-version                  go1.25.4 (gc)
ok        executable                  /usr/bin/chezmoi
ok        config-file                 found ~/.config/chezmoi/chezmoi.toml, last modified 2025-12-11T21:58:35+01:00
ok        source-dir                  ~/.local/share/chezmoi is a git working tree (clean)
ok        suspicious-entries          no suspicious entries
ok        working-tree                ~/.local/share/chezmoi is a git working tree (clean)
ok        dest-dir                    ~ is a directory
error     hardlink                    failed creating hardlink from ~/.local/share/chezmoi to /tmp: link ~/.local/share/chezmoi/.chezmoi-doctor-hardlink-test /tmp/chezmoi-doctor3479370187/.chezmoi-doctor-hardlink-test: invalid cross-device link
ok        symlink                     created symlink from .new-name to .old-name
ok        umask                       022
ok        cd-command                  found /bin/bash
ok        cd-args                     /bin/bash
info      diff-command                not set
ok        edit-command                found /usr/sbin/nvim
ok        edit-args                   /usr/sbin/nvim
ok        git-command                 found /usr/sbin/git, version 2.51.2
ok        merge-command               found /usr/sbin/nvim
ok        shell-command               found /bin/bash
ok        shell-args                  /bin/bash
info      age-command                 age not found in $PATH
ok        gpg-command                 found /usr/sbin/gpg, version 2.4.5
info      pinentry-command            not set
info      1password-command           op not found in $PATH
info      bitwarden-command           bw not found in $PATH
info      bitwarden-secrets-command   bws not found in $PATH
info      dashlane-command            dcli not found in $PATH
info      doppler-command             doppler not found in $PATH
info      gopass-command              gopass not found in $PATH
info      keepassxc-command           keepassxc-cli not found in $PATH
info      keepassxc-db                not set
info      keeper-command              keeper not found in $PATH
info      lastpass-command            lpass not found in $PATH
ok        pass-command                found /usr/sbin/pass, version 1.7.4
info      passhole-command            ph not found in $PATH
info      rbw-command                 rbw not found in $PATH
info      vault-command               vault not found in $PATH
info      secret-command              not set
```

</details>

**Comment by halostatue** [comment]
Thanks for a clear report; I don't use `exact_` or `re-add` myself, but can you run that last command with `--verbose`?

```sh
chezmoi --verbose -c test/chezmoi.toml -S test/source re-add dir/a
```

**Comment by r-ricci** [comment]
> chezmoi --verbose -c test/chezmoi.toml -S test/source re-add dir/a

```diff
diff --git a/exact_dir/a b/exact_dir/a
index ce013625030ba8dba906f756967f9e9ca394464a..14be0d41c639d701e0fe23e835b5fe9524b4459d 100644
--- a/exact_dir/a
+++ b/exact_dir/a
@@ -1 +1 @@
-hello
+hello2
diff --git a/exact_dir/b b/exact_dir/b
new file mode 100644
index 0000000000000000000000000000000000000000..ce013625030ba8dba906f756967f9e9ca394464a
--- /dev/null
+++ b/exact_dir/b
@@ -0,0 +1 @@
+hello
diff --git a/exact_dir/b.tmpl b/exact_dir/b.tmpl
deleted file mode 100644
index ce013625030ba8dba906f756967f9e9ca394464a..0000000000000000000000000000000000000000
--- a/exact_dir/b.tmpl
+++ /dev/null
@@ -1 +0,0 @@
-hello
```

**Comment by twpayne** [comment]
Thank you for reporting this. This should be fixed with #4862.

**Comment by r-ricci** [comment]
@twpayne
The issue still occurs with version 2.69.1. Here is a more clear script to reproduce the issue:

```sh
#!/bin/sh

set -ex

# create an empty directory to use as the $HOME during the test and cd into it
rm -rf chezmoi-test
mkdir chezmoi-test
cd chezmoi-test
export HOME="$PWD"

# create an empty config file
mkdir -p .config/chezmoi
touch .config/chezmoi/chezmoi.toml

# initialize chezmoi
chezmoi init

# create a non-template file, add it to chezmoi and make its directory exact_
mkdir dir
echo regular > dir/regular
chezmoi add dir/regular
chezmoi chattr exact dir

# create a template in the source and call `chezmoi apply` to add it to the target
echo template > .local/share/chezmoi/exact_dir/template.tmpl
chezmoi apply

# the file has a .tmpl extension in the source
ls .local/share/chezmoi/exact_dir/template*

# modify the non-template file and call `chezmoi re-add` on it (not its directory)
echo regular2 > dir/regular
chezmoi re-add dir/regular

# the template turned into a regular file (it no longer has the .tmpl extension in the source)
ls .local/share/chezmoi/exact_dir/template*
```

The problem occurs when re-adding a non-template file inside an exact_ directory which also contains templates. Re-adding the whole dir is fine.
