### ISSUE TITLE
warning templates/COMMIT_MESSAGE.tmpl not found when chezmoi edit exit

### ISSUE THREAD

**Issue by juxiemaotu** [twpayne/chezmoi#512]
#### Troubleshooting
- [x] I ran `chezmoi doctor` and fixed as many issues as possible and retried my command.
- [x] I have double checked the instructions for [Installation](https://github.com/twpayne/chezmoi/blob/master/docs/INSTALL.md) and the [Quickstart Guide](https://github.com/twpayne/chezmoi/blob/master/docs/QUICKSTART.md).
- [x] I have search for previous issues that have been reported/opened, and none of them relate to my problem.

Failure to follow the troubleshooting steps (and to report information requested below), may make it difficult to provide the proper support required. Furthermore, your issue may be closed without reply, if the instructions were not properly followed.

---

#### Description of issue

when i run chezmoi edit, it edit ok, but when i exit edit, it prompt warrning.Not related to the directory, it will be prompt:`{{.workdir}}/templates/COMMIT_MESSAGE.tmpl ....`
 how can i fix it?

#### Command that failed

```
chezmoi edit ~/.zshrc
```

#### Output of command with `--verbose`

```
/home/xxx/.nix-profile/bin/nvim /home/xxx/.local/share/chezmoi/dot_zshrc.tmpl
( cd /home/xxx/.local/share/chezmoi && /home/xxx/.nix-profile/bin/git add . )
( cd /home/xxxx/.local/share/chezmoi && /home/xxx/.nix-profile/bin/git status '--porcelain=v2' )
chezmoi: stat /home/xxxx/.local/share/templates/COMMIT_MESSAGE.tmpl: no such file or directory
```

#### Output of `chezmoi doctor`

```
ok: version 1.7.7, commit de864671370067dc78e51c272d27ac38b1391878, built at 2019-12-10T23:30:45Z
     ok: runtime.GOOS linux, runtime.GOARCH amd64
     ok: /home/xxxx/.local/share/chezmoi (source directory, perm 700)
     ok: /home/xxxx (destination directory, perm 755)
     ok: /home/xxxxx/.config/chezmoi/chezmoi.toml (configuration file)
     ok: /bin/zsh (shell)
     ok: /home/xxxx/.nix-profile/bin/nvim (editor)
     ok: /home/xxxxx/.nix-profile/bin/nvim (merge command)
     ok: /home/xxxxx/.nix-profile/bin/git (source VCS command, version 2.19.2)
     ok: /usr/bin/gpg (GnuPG, version 2.2.4)
warning: op (1Password CLI, not found)
warning: bw (Bitwarden CLI, not found)
warning: gopass (gopass CLI, not found)
warning: keepassxc-cli (KeePassXC CLI, not found)
warning: lpass (LastPass CLI, not found)
warning: pass (pass CLI, not found)
warning: vault (Vault CLI, not found)
```

#### Output of `chezmoi --version`

```
chezmoi version 1.7.7, commit de864671370067dc78e51c272d27ac38b1391878, built at 2019-12-10T23:30:45Z
```

**Comment by twpayne** [comment]
Thanks for spotting this. I missed a step when migrating the chezmoi release process from Travis to GitHub Actions, which meant that `COMMIT_MESSAGE.tmpl` and other files were not included in the built binary.

**Comment by twpayne** [comment]
I've pushed version 1.7.8 of chezmoi which includes the fix.

**Comment by CosmosAtlas** [comment]
I'm still having the same issue with version `1.7.15` on archlinux.
